version: '3'
services:
  camera:
    # container_name: camera
    build: .
    tty: true
    environment:
      TZ: Asia/Tokyo
    devices:
      - $CAMERA_PATH:$CAMERA_PATH
    volumes:
      - ../src:$WORK_DIR
    working_dir: $WORK_DIR
    # command: ls ${CAMERA_PATH}
    # command: v4l2-ctl --list-devices
    command: bash -c "
      python main.py
      "